# Reference: https://docs.docker.com/reference/compose-file/
name: remote-access-tool

services:
  ubuntu-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: bash -c "(yes | ssh-keygen -t rsa -f host -N '') && rat-server -k host | tee /var/log/rat.log"
    container_name: ubuntu-server
    healthcheck:
      test: cat /var/log/rat.log
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 3s
    hostname: ubuntu-server
    image: ubuntu-server
    stdin_open: true
    tty: true

  ubuntu-client:
    build:
      context: .
      dockerfile: client/ubuntu.Dockerfile
    command: rat-client ubuntu-server:22
    # container_name: ubuntu-client
    depends_on:
      ubuntu-server:
        condition: service_healthy
    deploy:
      replicas: 3
    image: ubuntu-client

  centos-client:
    build:
      context: .
      dockerfile: client/centos.Dockerfile
    command: rat-client ubuntu-server:22
    # container_name: centos-client
    depends_on:
      ubuntu-server:
        condition: service_healthy
    deploy:
      replicas: 3
    image: centos-client
