[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
colog = { workspace = true }
common = { path = "../common" }
log = { workspace = true }
tokio = { workspace = true, features = ["full"] }
