[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
colog = { workspace = true }
common = { path = "../common" }
env_logger = "^0.11.3"
log = { workspace = true }
shlex = "^1.3.0"
ssh-key = { workspace = true }
tokio = { workspace = true }
