name: Lint

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  clippy:
    name: Run clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        run: curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=1.87 -y

      - name: Run clippy
        run: cargo clippy --all-features --no-deps -- -D warnings
